#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
	0x01,0x04,0xc1,0x68,0x39,0x9b,0x20,0x8d,
};

static const uint8_t chainparams_seed_test[] = {
	0x01,0x04,0xc1,0x68,0x39,0x9b,0x20,0x8d,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
